[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
fnv = "1.0.7"
hashbrown = "0.15.2"
indicatif = "0.17.9"
itertools = "0.13.0"
num = "0.4.3"
rayon = "1.10.0"
regex = "1.11.1"
rustc-hash = "2.1.0"
